// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.DataAccess.DataContexts.GeneralSettings;

#nullable disable

namespace ProductManagement.DataAccess.Migrations
{
    [DbContext(typeof(GeneralSettingContext))]
    [Migration("20250312142841_InitialMigration_GeneralSetting")]
    partial class InitialMigration_GeneralSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.DataAccess.Models.GeneralSettings.RefUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DtmCrt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtm_crt");

                    b.Property<DateTime?>("DtmUpd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtm_upd");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)")
                        .HasColumnName("guid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("username");

                    b.Property<string>("UsrCrt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usr_crt");

                    b.Property<string>("UsrUpd")
                        .HasColumnType("longtext")
                        .HasColumnName("usr_upd");

                    b.HasKey("Id");

                    b.ToTable("ref_user");
                });
#pragma warning restore 612, 618
        }
    }
}
